sudo: required
dist: trusty
git:
        submodules: false
language: c
compiler: gcc
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
env:
        global: TOPDIR=`pwd`
script:
        - mkdir -p $(TOPDIR)/tmp/binutils
        - cd $(TOPDIR)/tmp/binutils
        - $(TOPDIR)/RWTH-OS/binutils/configure --target=x86_64-hermit --prefix=$(TOPDIR)/x86 --disable-shared --disable-nls --disable-gdb --disable-libdecnumber --disable-readline --disable-sim --disable-libssp --enable-tls
        - make
        - make install
