sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
  sshpass
env:
  global:
  - TOPDIR=`pwd`/../..
script:
- mkdir -p $TOPDIR/tmp/binutils
- cd $TOPDIR/tmp/binutils
- "$TOPDIR/RWTH-OS/binutils/configure --target=x86_64-hermit --prefix=$TOPDIR/x86
  --disable-shared --disable-nls --disable-gdb --disable-libdecnumber --disable-readline
  --disable-sim --disable-libssp --enable-tls"
- make -j2
- make install
after_success:
- cd $TOPDIR
- tar -czvf binutils.tar.gz tmp x86
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp binutils.tar.gz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
   global:
     - TOPDIR=`pwd`/../..
     - secure: "mY/m7mc2g0l6zpqo/1XwYHGd3dJtyTqH0EufN44vhplY6/+D5XlwqoZ/ussG05iaR10dCvTNjNHtEW+QrsGjl22RoRJFSLQ/1K0c4UPORAJdlibjR4vRb5P1/tmJQWelSKPT9GwA2rZs0KZhUGesx7NHwAxC5C9nlLXLIg4YpTnrQS/zt3dgPF/4vyaGl29sacPobxrEL9VMzMHoxN0CPkqKO5T/6htXzZfAF80FjJ4FauVMX5grPTbfTCGeFRS2AGyDyEkK9ATw/JWSyo6p82I2mknhzxaDdxI5NQavynFY7LKLB4c8QQ25C7a50PSeGembT6tNaMuAiUiGgZppb99WRBAOyp31PE4tQ/LQAa1CO49oZY4OcTaiy86b2pGxraz1IOwzhfCfQVEGEHDWE9BX9Oxi5Nerh8ObBbtCVez6Yro1dDxMD+7lH+PyVGamjybcb3LFloiAnWASw3jy1+fz+MutzPHfMLrr805fOaICtGs1MQU/qmdI9E6x3ibmrsciRZGX8ywIMeylkiXlmFc76iWnu4dWsEnsxlwL+Z0O9BhgU5StA64c0pXul0LBuIZtB/ujBQysPNXatopZgEwCnWiAokgCvwjCM0G0OH/t2be6yt784kd7Bw8I2GmuVsyavWnJ/YOo4EZiKLyasS+40tLyqhq4UtY12tyouG4="
     - secure: "lK7OZBX9PO1ti9Hij/czb34psGzrCHOO/+PxqX6OS8Eekw43EfdPP+SPy53wrA6TE+XgJ9fvtGM0rKCgzMPK3nl41U4NFMSj6r+NY41H6cWYoluQEmxIQuYaZ316MT7ktIaw8CRnoZk4tnl92fr9MQJ6H+1+JUp/jiNg3ia0VMsGWmuESB2I9yaBd54PRulrhxFhJkcZVCtQ+9uKdm9xt7AsMFb/5WDGkmdkbARa5MRcZF1/zI8x3eUFlSigfR9pDOKFVA18CSAuWTtkS1oGxAMhLP/sNxaU5xx4ny3F1qwol8SQN5dOPu/Yx/mS2NbaMmuOJPSJUoDHgbpi4dyLCD2iW/oFdPobb17unIn1SLKwzLPoffqocj2u5fBcqswGJ95g7eMmZ98goprMDwS9rFltEIsT6LanyIPU+EWjJdQx7l7Y+kTvXQUM1+foOqNJEvDqsxO44+oX9d8aMbJf5bVXUmc9ez4b8u7hJniy+C1UrEWBRrBWXPw70qCft9de5jISl1ZLI8B6xPCjuAegwWzKQfk3540sfuz2IALsJ8Jj4kMCFWAIUnB+Xl1v16WMY3GLyDAxMmGqb4yLtOZvA0j81G9cP7R+iRWQOM76eVRros0B+DXrgw41zsLliMupIvavT2LcriWnXjebKO7Hjs2gjaUQibWMyXdW5wiTqiY="
     - secure: "Imcz+oZT/Ip/kZ8UsVr/U39HwFLyn/VSHcyFda5O8QCeTEQ7CTPE3rRbRo1rz5wej7aRas8vKdkQOd8vXu4LNmwkuehMt5lpAZozpmmJLk+cNOwxO7UOuQZfZey1HTiQAVMZFRjkG0qo0YaGl9SWe6Cmp1tneD0AfxdC+D+86rcO8NrrEdzpf8lQI7hcY5PwdRQExRcAZVv7WEGkzzieqPUK/5pzseMxKpPYhydQlkJvF4kidzJAbDoM9021JNpfQGBnOwFEDVB3tDE4S4F6XUrZGZcmJH4zS2Xn501NV6zqk/vjDhWeippeR9yB2Qbk695G0tLyHPjBf1g3P8wcxwwh10OKXEp8OnLy24NEgKerDs3ZqPByuzkcjG5nTouxtCD+mYpxDhZynCfnLK3/gbn1KZx5Ae9lq3txg1B1xwSaS3VNnpEjrJXV4HyXIG7LMckAMTh3WNJhbEOMjR0Vhgz3aiRCxp94lJRe9+mwQPVTsS/mm1i/Fs3ZUtHQwaWiUkaTjiyhUiXmYF1dxJ8BFS3dhX0df9eufRNIFTK0qU1mhuGmfG9rPKmUYMZTz6vMGgH2SW4k6mnu0Iw/y9rGPcxvRRwCdjbfWOzPQ/O/d/mXOmmEe9GOiVPf1uVjlvT1Obpc1hWwSnht8beolV5YWmHnNWAMwRUgKymzcTAlFqg="
     - secure: "BlCcZI4CHS1QNxFBysZezFUZuEM5kM+QNEWZfRRBEE8zM5iqOspP3TTASM4WWLRHgVsKpC6xIUNggJ+pxXaumJudF/zrkFyArYNzEJDVFojWPKOdKa4I9hCBoiIu7mXDUwNa9NEl3UCzX/ASo4B4dXfPi4OIbvV/1TjUfaDJG51vlLaWgJC0mQ7pSAFVEB3d16lSwQ4KyubdRT+8rH3AjkaFdzKCrb5tPxTjQNc2Vfr5IBvuTiR+w8fKGVO7W22nQgPdNHpnA1Ix13ndNGqzrf0hw9VJX/I5Xo8oN2RjNeAKMesrurkxLXF0pi9e+CerDFiTATIPio+Ak9fwcOs3rw8/aGZ9DOHd3BzomVLi2VNvqDUGgulowSEFX0H9y2snf1zinWt0CRE4nVG4Lcg4yWG3gAe6clazpDIXpVoLgcecgfv3F+P8hQMSLTxhMWr8TxmMpf8yXFQaT1RCrZmO8ns9oD0NercWWFneXe3dPQUKPYc0C9Mn75kaQ4+cOT7+bA2UAu0Wr0Rb2R4WhUd1T5bLL8r8f6bEXs2W2fIdMjT7Wl+psoH4X1xJqhxkd7Zq7jdzc2XCN6c/JuOUMZD2V5OrU666wrv1X6QM8EwxVsEEoQkT8/y+5aCPJTA3+7CemeitP9lSmBwr65MG2E6KppglGG6EffJrRgy8MhFJ+9U="
