sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev packaging-dev sshpass
script:
- mkdir -p $TOPDIR/build/binutils-2.26.1
- cd $TOPDIR/build/binutils-2.26.1
- "$TOPDIR/RWTH-OS/binutils/configure --target=x86_64-hermit
  --disable-shared --disable-nls --disable-gdb --disable-libdecnumber --disable-readline
  --disable-sim --disable-libssp --enable-tls --disable-multilib"
- ls -la
- echo " " | dh_make -s -e slankes@eonerc.rwth-aachen.de --packagename binutils --copyright gpl2  --createorig
- cat debian/rules
- ls -la
- debuild -us -uc
after_success:
- ls -la
- ls -la debian
- cd $TOPDIR
env:
   global:
     - TOPDIR=`pwd`/../..
     - DEBFULLNAME="Stefan Lankes"
     - DEBEMAIL="slankes@eonerc.rwth-aachen.de"
