sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
  sshpass
env:
  global:
  - TOPDIR=`pwd`/../..
script:
- mkdir -p $TOPDIR/tmp/binutils
- cd $TOPDIR/tmp/binutils
- "$TOPDIR/RWTH-OS/binutils/configure --target=x86_64-hermit --prefix=$TOPDIR/x86
  --disable-shared --disable-nls --disable-gdb --disable-libdecnumber --disable-readline
  --disable-sim --disable-libssp --enable-tls"
- make -j2
- make install
after_success:
- cd $TOPDIR
- tar -czvf binutils.tar.gz tmp x86
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp binutils.tar.gz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
   global:
     - TOPDIR=`pwd`/../..
     - secure: qMY7gO3380NNAsWSr0jDBZVwGbcBDTVgwXUcKqs7ZgvmiyXa/MCw+JjFyciQo9caJ1OZ7qaZEJNhIzoJ9p6vfiBDd7GqCE5K8gVzwLgJjvvTAwCkh8U8W3I0tBHDEmr+mbo75eoXmGVcerD0QNtRPamblTjv8VCjDHu0CXL0h+g2Pd0Pxna4+dm5f68QDL/V/pH+LOOOD6FZ5SB8tgSagchpaZzzXibqREHj3Rq1gfOXJrOWNwKRN1cxBEK8dLoDabeDu9f3pZEShGdH2K3D3y7QaDKpU1KxsvFgSTFxW1w7G20j6a9eT6Ph16qLngkZ5t8kdfjOgw9Lc+xfyx8fP5GaOxU6bQItXS9sPzG0f+uMzTa0DRTNdPLhpYxWKNeVvs6J5AkM2sVTLfqeunTLK7NuVX5pL/gPrqVdd/0HdQvF8ve7Wr5TXB+nq6RVamJs3dk/cP8TcUsyhIacL5XGJxu5MQi1Pmamw/20YnesrE3FE6PQUo5MBT+hsWSIsA2NbljBnDZYCRFcH9UskXWT9JNOOj26AMES4lNMzxPkuRHlCG4SDJxZcmFpW1rC1bDZtQVb8xzRLOK80cVswSDNLpIjpVTjohnELKkZfh0oFDYpaGWPzVGoSZ+nUhWd8enxnhM6wihatw0/90vNmXusIk0oabW4duTVXRcOryLQd84=
     - secure: bhUWyrEuEpf7BL2YRtduqMC+Oxro++z07/FTGh3YOt8tfgKsf9A/NtWstq7KcYkfFHRDV28pGzXyaOZfmGZ9En6nX03GC8/haY2GWWelsYkEFHzOayg0dkVa1uGDWjlzQCnL6BKVwRXOWiXmCKtNFHhX3LHXcoKmoJhwRHVVJG1czLMNFGRPcLROnySRa3b+5mlakbEPtVuTyCRc3r9mIExqPbLd8U+XEpK1ruFAfcsTXNdp5ZutUVR1YfvNEjhmJYyOkqu2/yoRL1gB3/HTyV65DpKJm+oPVkq0zcPOoOoTvVsBamhLGCCDHwGi+xPPJiivmPUkhuLnaH42/ehxpycv/2fMGgxcbYJlt3ud3U3yh72FOk3l1/Nvdyd+JDbLhD64PfPCskFxseJXR72Yps18sZ7viwxDvI39YYmrWtuxCl6rfWxr42uTcAzc/vTTC4wqPRmVfoMQjUAZKHrBglyglWw2Fpu3V1la2FiTQTznZD06WKHLBqt0ommbtFcm5iIbyt4aUuTBD2ke1JzPVWB3/trZY6CHL/c5aW+7KDtKr38exk8+XySwNIwdYpynLgKJEkVpPlJfUO6EU1ht60wpp3sSBVxZyG1ag9AfqCOIkdOmtv9KvPEArrYVwvfix9ye9b+Wsg89uy3SRN/8H4i98kPcBwgjgZznOy9pifc=
     - secure: L666NBoojLDzudRo2ocmAdzEwIVT6SN0WOjO42dttorC3p5eYwc3yukwBkHrqrNR8p3+uWpg/b2HiZI8Fl+sthbm8mNHO+3loNea+s6XhMgo3bbxAGYqFbDy0vZflYY4liS1uGpUJ9gythCbQgjcull2+xrsfb7mDDwfJZQJweo1SYzAUOhm9YyzXSR+0gJZiJISi+PkTVahvbcn25aTMaFRqb17r7uR6WqvhCwd33yKtojkQHa15TU+GMbBciHFWx5P7oi6MZnehuxT5Us8d0RgwNWUPDP7spHJ3OmQqcZmJ2j4A35Xevkq4DbwiypVCwL0lXLnugDL7X13zpxYcQl1LNYK8LQ2jgxNHT582wwgbhj9/FxNapZcS1IeLaZSlEhF+yHbieDNZrIFCwSZtWqlUXpR8mS0fUDV5mY2sM9kK/NmXJMfA9dnfPRc3Zjg8Q7jZG6xgOiACcJ4qS8fA21zmpMsV4VsqfdKZ+GIr2s9G+jetPn1tsdxJZJQnOmtd6v7U6lF419foAdbf+fg6S4ZG0smdRt4bGkcF5XC2b4ZluHCJTMdhrAgHXzJ5opo396Z/cZLdkqc0bPKdxrnyF35jU5T6XfbXaFegLlQomOAgG7HtqUBJTdcQsvMcGt5T7mW7WZDJ4bL1IFiiNukdy3Edu4mUJYn2FiFqKPzPMw=
     - secure: Z4Nb6PocubVCJksCS0vYyV5zeym7bijRg3ror+L9VSntrL7Z3a9BXLg9vQmL51QyutjP2AVTuen9D+iM+Bn47Jges5kkkH/vG3tX3Fvwhor0qqlB7b2OaVeCBrln4jTgrDfwIYoCZxFZj8hgRdQrgtf0KTcvW5mSqulCgG2J2WTfzi4OoM4fss8d6ZYRiWaHy/YMcudUnmJFnSZ58PTzHyTX6i/E8FA+QnJxS24wVvIEw8dEmq2o1ojOzZfYNi0uBXKUVs/o1KPY5iBrfopvhnU0DByIFf4GvGNqnVSNv1RB2frE9up2GC5zQ0JFkzzWO1PHux3UpKC2SxNZQHPpNpbyJ8lf8nVdxzEa2+BQuWXfHieZdnj3mYtsxG6yD9N5ua8OCGHfNYTVHAQ0aV676N44bNit5Lfhg6J5ZCObyuEfK5PQNz2neP1bDj4ACFA2DRo8I6/8jRiWGcsN5Sa8LLk9VCdWKSx15DEpUB/DHt+CYPehn/N3FbU37mWoTB8Xpd/hDgc0vA1hl3+b7kaSrVgmaRNzbatF8aJSf/6e4gz1Q7dq7QvKSbxkfSZRb1Mf/HcdO8liIEl+C+M51Up9r/icSQTp/LXR+Da37P9jTunvOKcC9Y+QnwnQyuJkxaTjWs7xLOhMxTcdv0xVdaiqVAbYhko1zW+mZ9TSIOLf3SI=
