sudo: required
dist: trusty
git:
        submodules: false
language: c
compiler: gcc
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
before_script:
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        - export PATH=$PATH:/usr/local/bin
        - export TOPDIR=$(pwd)
        - export TARGET=x86_64-hermit
        - export ARCH=x86
script:
        - mkdir -p ~/tmp/binutils
        - cd ~/tmp/binutils
        - $(TOPDIR)/configure --target=$(TARGET) --prefix=~/$(ARCH) --disable-shared --disable-nls --disable-gdb --disable-libdecnumber --disable-readline --disable-sim --disable-libssp --enable-tls
        - make
        - make install
