sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev packaging-dev sshpass
script:
- cd ..
- mv binutils binutils-2.26.1
- cd binutils-2.26.1
- debuild -us -uc
after_success:
- cd $TOPDIR
env:
   global:
     - TOPDIR=`pwd`/../..
     - DEBFULLNAME="Stefan Lankes"
     - DEBEMAIL="slankes@eonerc.rwth-aachen.de"
