sudo: required
dist: trusty
git:
  depth: 3
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
  alien packaging-dev
script:
- rm -rf .git
- cd ..
- mv binutils binutils-2.26.1
- tar -czf binutils_2.26.1.orig.tar.gz binutils-2.26.1
- cd binutils-2.26.1
- time debuild -us -uc -j2
- md5sum ../*.deb
- sudo alien -r ../*.deb
- sudo mv *.rpm ..
deploy:
  - provider: bintray
    on: production
    file: ".bintray_descriptor.json"
    user:
      secure: Qx2DhypCaucQiSIUkQqQxUPRp+XphKgVtscU7gtJ6WOV9n+6PPxCYv8jbDR0bDV4SGytRgD5rbh7r/XoqPxfVfj1VuH5k/VGb3OCEBoEW7a60PXbXfM2rWAuSuExH4GfeG+hQMr1w5DDk5u4M2owcQY9kUZ/N9VWaZ5U7+p3ZGRbzn+5GNHtVeHj7w7w/6xQmvYIDrUyBf2p0SGv/9Ktlo3Hx/oDhFTlywQUM96Pyc+UufsbTjA9wsNyTyThRcyBhQk1WSmcH5Bw5QmMHNtbDIKDajl2AyVLJrADRnJNpTN7hj23UZ6lVWH0b0LEwV/l8L0qfI1BzSV7BX8Yu2o0SzyYvVcfhRNQM6kptdawHLIMqzZUW/TI+YJjdmT8YeHNYcdBVRcaW4JbCmBIwgv7u/iL+b1Ou29t39rMYhcIE8uk+xDC8D8y7VcxZLmxDMYgzgU7FSxULJe0p2blcHO2k1py/KHErEIHrAx4ART3YsAhFTQQZb0BebNqMRfWlJSWE8EWU9QNi+H1dzrhNmOHeF6mM31cm45cQP683Wb0nz0vaty6S9s+Y39lAEkT/Yd7LZRoV0fW4jdA7INFp/DBfmeBOeZsJ2Y9+K/SC0jiymF2l0ZOTyegl+PQ6CKiwd8fpj28mpovOTZvfPWjlMIzAmj01ur9FioDTQgdDfLPovo=
    key:
      secure: glmIr26BV2ntaRauAoOp1yv8xuGzg2zrBEDyYbGSMIi30PLWolxRvR+r3tszzePHU3nhWOzIsJg2rSnanHNRPc7pRgL07cPZ80Pzuzu2AQMJleScnX158xKMnNcieimdi/Uy1oCpI9Iz96Amcf7r2x9Jk9R4/hrNCUeFu8z0VkTvx3a12aKt2/IFRgwp8MoVLRmIWUHu61q+nD+LroIo4/4if00Mn3KQ0cnY5qPZR3Nw+xQ4bsWgpNwYd6r8R7cVOtMFujCrpLSJ65ogoYxgvaI0OENgL44ETXPhj0jDK5fQ6rCm+0NEq29Z9lSkJKqw1eK7op4xijYZWG7qGe80x74H4j+0V4nLuzmHV2+vBJt/bRccN+FZfPhnWJ48RmGW74XcbewMq8JjRyuBaNrIJi3qHRJ/+BrcbS76jG+AuJn9N7jkRdWNomAtjt2YKqfsjFgNa6BuMwoavhqqolfIJs+v1eHEvAXwX1aiPF/FJdkvcQpeWewgCK2rOsX5nCNLW1pWnT0nr8zqfe4+hJUscRRA3JJTmjHFzGbw1jIjHRaV3eGT8xy0zLlmw+0fYzaK0jS5BlxG9kQkFxLb0enq8YG4QcQNSRXbwMr70sL50OHZXJ8aQt+ccFQH0OS9UDkVPQ+630T/xLyX7iL9gqG2A/7GfzsZHPQ2bvzYd79M5AY=
  - provider: packagecloud
    on: production
    repository: hermitcore
    username: rwth-os
    dist: centos/7
    token:
      secure: K8twOY9LSP94errqBTtoclPZps5a4iDEvayjDwOLL8e8f11a4ApCKl4Rhr/2y0qShI7nY8zXfhwzTPwIkZyjEfQFvNf7IflDRggfOM0cO+kizlccPkvBTJ0WPAVRmzAfhuUrclQGcKjaJww0o5WXNuVf0ds7mSIkxO5N0PadL+msK/yzedelUJtzippe2BbXT2/q8IbJvQEmIGWeTUvPD9SX/26Snjx2zkrgHzp5kI0LMTVXOQQ3kQm6CxLohVULe1SoJRKTLSxKjOENCNJbqNYXC3Kq5kOkZjE7CEUABRuMaS2em9mw+qauk8AwatBzr3zE2x5N2RL9wp1OZwLViF/O2wEsUm0Ly1fLXL6HaHcbdFDQltckE2DuIA1YQ9LBm4xj/m+7omhHUIjIe2ElfJQdPaPxjPsZRZt8cIbGtS5UAjX6skZelxtiVliyOhTmJL/geMUuubZFTFdIzTkLBe4bfO84vsOTDOVQJ7pcxzmTrV8CXCpLI39lB3Yv5cffTJvj/51rdV9FZ1LzdNxIPOtwXve5CLrUldSacjgmhhgLpx78/9W9kyR/FjYgOnDixuisNQC1NSvvv6QXckSFPRJf25CJ+TW12vPuy5/Bs/5mWMJ/Yf9d/MX+Rh299KL0z2/N7s7q/20hHXywhe5W6wMjE7KDXTwCx55MOBNDsz8=
